language: cpp

cache:
 - apt


addons:
 apt:
  packages: lcov

before_install:
  # we need a recent version of CMake
  # linux prereqisite packages
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzvf cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi

env:
  global: TEST_NAME=""

before_script:
 - echo ${TEST_NAME}

matrix:
  include:
    - env:    TEST_NAME="gcc-4.8 (CMake)"
      compiler: gcc
      script:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get install -qq -y g++-4.8
        - export CC="gcc-4.8"
        - export CXX="g++-4.8"
          #        - mkdir cmake-build && cd cmake-build && cmake -DENABLE_TESTS=ON ..  && cd ..
        - CXXFLAGS="--coverage" cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CRYPTO:BOOL=OFF -DENABLE_DATA:BOOL=OFF -DENABLE_JSON:BOOL=OFF -DENABLE_MONGODB:BOOL=OFF -DENABLE_NET:BOOL=OFF -DENABLE_NETSSL:BOOL=OFF -DENABLE_PAGECOMPILER_FILE2PAGE:BOOL=OFF -DENABLE_PAGECOMPILER:BOOL=OFF -DENABLE_REDIS:BOOL=OFF -DENABLE_UTIL:BOOL=OFF -DENABLE_XML:BOOL=OFF -DENABLE_ZIP:BOOL=OFF -DENABLE_TESTS=ON .. && make -j2

after_script:
  # Create lcov report
  - lcov --capture --initial --directory .. -o app_base.info
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove app_base.info */tests/* --output-file app_base.info
  - lcov --remove coverage.info */tests/* --output-file coverage.info
  - lcov -a app_base.info -a coverage.info -o coverage.info
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
